//! RAGFlow QA-stage chat pipeline — `retrieval → prompt → generation → citations`.
//!
//! Ports the question-answering stage of RAGFlow into RayRAG:
//!
//! 1. **Question rewrite** — `rag/prompts/generator.py::full_question`
//!    (`RAGFLOW_FULL_QUESTION_PROMPT`): rewrite the latest conversation turn
//!    into a standalone question, converting relative dates to absolute ones.
//! 2. **Multi-query fan-out** — `generator.py::multi_queries_gen`
//!    (`RAGFLOW_MULTI_QUERIES_GEN_PROMPT`): when the first retrieval is weak,
//!    ask the LLM for 2-3 complementary queries and merge their hits in front.
//! 3. **Prompt assembly** — mirrors `api/db/services/dialog_service.py`
//!    `async_chat`: knowledge is rendered with the RAGFlow `kb_prompt` tree
//!    layout (`ID: i` / `├── Title` / `└── Content`), and the citation
//!    guidelines (`RAGFLOW_CITATION_PROMPT`) are appended when citation
//!    formatting is enabled.
//! 4. **Citation formatting** — `citation_plus` second pass
//!    (`RAGFLOW_CITATION_PLUS_PROMPT`) over the generated answer, followed by
//!    `dialog::repair_bad_citation_formats` to canonicalise `[ID:n]` markers
//!    and collect the cited chunk indexes (port of
//!    `dialog_service.repair_bad_citation_formats`).
//! 5. **Reflection** — `generator.py::reflect_async` (`RAGFLOW_REFLECT_PROMPT`):
//!    optional post-generation reflection; optionally re-generate the answer
//!    with the reflection appended to the system prompt.
//!
//! Every stage is off by default (`ChatPipelineConfig::default()`), so the
//! pipeline behaves exactly like a plain retrieval → LLM answer. Switches are
//! enabled via environment variables (`RAYRAG_CHAT_*`) or KB flag maps
//! (`apply_kb_flags`, keys `chat_*`).

use crate::dialog::{extract_cited_indexes, repair_bad_citation_formats};
use crate::llm::{ChatMessage, LlmClient};
use crate::prompts::PromptLibrary;
use crate::search::{HybridSearchQuery, HybridSearchResult, SearchEngine};
use std::collections::{HashMap, HashSet};

/// Default system prompt used when the pipeline runs without an explicit one.
/// Mirrors the inline prompt of `server.rs::chat_completion`.
pub const DEFAULT_CHAT_SYSTEM_PROMPT: &str =
    "请基于以下知识库内容回答问题。若内容不足以回答，请说明。";

/// Minimum hit count below which the multi-query fan-out is triggered.
const MULTI_QUERIES_MIN_HITS: usize = 2;

/// A complementary query generated by `multi_queries_gen`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MultiQuery {
    pub question: String,
    pub query: String,
}

/// Outcome of one pipeline run.
#[derive(Debug, Clone)]
pub struct ChatOutcome {
    /// Final answer (with think prefix preserved when the model emitted one).
    pub answer: String,
    /// Question actually used for retrieval (possibly rewritten).
    pub question: String,
    /// Cited chunk indexes (0-based into the retrieved chunk list).
    pub cited_indexes: HashSet<usize>,
    /// Retrieved chunks (cited ones only when citation formatting is on).
    pub references: Vec<serde_json::Value>,
    /// Final system prompt (for tracing / debugging).
    pub prompt: String,
    /// Reflection pass output (when `reflect` is enabled).
    pub reflection: Option<String>,
    /// Queries generated by the multi-query stage (when enabled).
    pub multi_queries: Vec<String>,
}

/// Pipeline switches — every feature defaults to **off**.
#[derive(Debug, Clone)]
pub struct ChatPipelineConfig {
    /// Rewrite the latest turn into a standalone question (`full_question`).
    pub full_question: bool,
    /// Fan out into 2-3 complementary queries when retrieval is weak.
    pub multi_queries: bool,
    /// `top_k` used per generated multi-query (0 = reuse `top_k`).
    pub multi_queries_top_k: usize,
    /// Citation formatting: `citation_plus` second pass + `repair_bad_citation_formats`.
    pub citation_plus: bool,
    /// Post-generation reflection (`reflect`).
    pub reflect: bool,
    /// Re-generate the answer with the reflection appended to the system prompt.
    pub reflect_regenerate: bool,
    /// Base retrieval `top_k`.
    pub top_k: usize,
    /// Vector weight for hybrid search (0.0 = term-only, 1.0 = vector-only).
    pub vector_weight: f32,
    /// System prompt override (None = `DEFAULT_CHAT_SYSTEM_PROMPT`).
    pub system_prompt: Option<String>,
    /// Language hint for `full_question` (None = auto-detect CJK).
    pub language: Option<String>,
}

impl Default for ChatPipelineConfig {
    fn default() -> Self {
        Self {
            full_question: false,
            multi_queries: false,
            multi_queries_top_k: 0,
            citation_plus: false,
            reflect: false,
            reflect_regenerate: false,
            top_k: 4,
            vector_weight: 0.5,
            system_prompt: None,
            language: None,
        }
    }
}

impl ChatPipelineConfig {
    /// Build the config from `RAYRAG_CHAT_*` environment variables.
    /// All flags stay off when their variable is unset.
    pub fn from_env() -> Self {
        let mut cfg = Self::default();
        cfg.full_question = env_flag("RAYRAG_CHAT_FULL_QUESTION");
        cfg.multi_queries = env_flag("RAYRAG_CHAT_MULTI_QUERIES");
        if let Some(v) = env_usize("RAYRAG_CHAT_MULTI_QUERIES_TOP_K") {
            cfg.multi_queries_top_k = v;
        }
        cfg.citation_plus = env_flag("RAYRAG_CHAT_CITATION_PLUS");
        cfg.reflect = env_flag("RAYRAG_CHAT_REFLECT");
        cfg.reflect_regenerate = env_flag("RAYRAG_CHAT_REFLECT_REGENERATE");
        if let Some(v) = env_usize("RAYRAG_CHAT_TOP_K") {
            cfg.top_k = v;
        }
        if let Some(v) = env_f32("RAYRAG_CHAT_VECTOR_WEIGHT") {
            cfg.vector_weight = v;
        }
        if let Ok(v) = std::env::var("RAYRAG_CHAT_SYSTEM_PROMPT")
            && !v.is_empty() {
                cfg.system_prompt = Some(v);
            }
        if let Ok(v) = std::env::var("RAYRAG_CHAT_LANGUAGE")
            && !v.is_empty() {
                cfg.language = Some(v);
            }
        cfg
    }

    /// Merge KB-level flag maps (e.g. `kb.config` entries). Recognised keys:
    /// `chat_full_question`, `chat_multi_queries`, `chat_multi_queries_top_k`,
    /// `chat_citation_plus`, `chat_reflect`, `chat_reflect_regenerate`,
    /// `chat_top_k`, `chat_vector_weight`, `chat_system_prompt`, `chat_language`.
    /// Values `1` / `true` / `on` / `yes` turn a flag on.
    pub fn apply_kb_flags(&mut self, flags: &HashMap<String, String>) {
        self.full_question |= kb_flag(flags, "chat_full_question");
        self.multi_queries |= kb_flag(flags, "chat_multi_queries");
        self.citation_plus |= kb_flag(flags, "chat_citation_plus");
        self.reflect |= kb_flag(flags, "chat_reflect");
        self.reflect_regenerate |= kb_flag(flags, "chat_reflect_regenerate");
        if let Some(v) = kb_usize(flags, "chat_multi_queries_top_k") {
            self.multi_queries_top_k = v;
        }
        if let Some(v) = kb_usize(flags, "chat_top_k") {
            self.top_k = v;
        }
        if let Some(v) = kb_f32(flags, "chat_vector_weight") {
            self.vector_weight = v;
        }
        if let Some(v) = flags.get("chat_system_prompt")
            && !v.is_empty() {
                self.system_prompt = Some(v.clone());
            }
        if let Some(v) = flags.get("chat_language")
            && !v.is_empty() {
                self.language = Some(v.clone());
            }
    }
}

/// The chat pipeline: retrieval → prompt assembly → LLM generation → citations.
pub struct ChatPipeline<'a> {
    engine: &'a SearchEngine,
    llm: &'a LlmClient,
    config: ChatPipelineConfig,
}

impl<'a> ChatPipeline<'a> {
    pub fn new(engine: &'a SearchEngine, llm: &'a LlmClient, config: ChatPipelineConfig) -> Self {
        Self {
            engine,
            llm,
            config,
        }
    }

    /// Run one QA round over `kb_ids`.
    ///
    /// Stages (each gated by `ChatPipelineConfig`):
    /// 1. `full_question` rewrite (when history is present)
    /// 2. hybrid retrieval
    /// 3. `multi_queries` fan-out when the first pass returned < 2 hits
    /// 4. prompt assembly (`kb_prompt` layout + optional citation guidelines)
    /// 5. LLM generation
    /// 6. `citation_plus` second pass + `repair_bad_citation_formats`
    /// 7. `reflect` pass (optionally re-generating the answer)
    pub async fn run(
        &self,
        question: &str,
        history: &[ChatMessage],
        kb_ids: &[String],
    ) -> crate::Result<ChatOutcome> {
        let cfg = &self.config;

        // 1. Question rewrite (full_question)
        let mut final_question = question.to_string();
        if cfg.full_question && !history.is_empty()
            && let Some(rewritten) = self.rewrite_full_question(question, history).await? {
                final_question = rewritten;
            }

        // 2 + 3. Retrieval with optional multi-query fan-out
        let mut hits = self.retrieve(&final_question, cfg.top_k, kb_ids);
        let mut generated_queries: Vec<String> = Vec::new();
        if cfg.multi_queries && hits.len() < MULTI_QUERIES_MIN_HITS {
            let retrieved_docs = hits
                .iter()
                .map(|h| h.chunk.content.as_str())
                .collect::<Vec<_>>()
                .join("\n");
            if let Some(queries) = self
                .generate_multi_queries(question, &final_question, &retrieved_docs)
                .await?
            {
                let per = if cfg.multi_queries_top_k > 0 {
                    cfg.multi_queries_top_k
                } else {
                    cfg.top_k
                };
                for mq in &queries {
                    generated_queries.push(mq.query.clone());
                    for extra in self.retrieve(&mq.query, per, kb_ids) {
                        if !hits.iter().any(|h| h.chunk.id == extra.chunk.id) {
                            // RAGFlow inserts multi-query hits at the front.
                            hits.insert(0, extra);
                        }
                    }
                }
                hits.truncate(cfg.top_k.max(per) * 2);
            }
        }

        let num_chunks = hits.len();
        let knowledge = format_knowledge(&hits);
        let msgs = build_answer_messages(cfg, &final_question, history, &knowledge);
        let prompt = msgs[0].content.clone();

        // 5. Generation
        let mut answer = self.llm.chat(&msgs).await?;

        // Split off a leading think block, like RAGFlow `decorate_answer`.
        let think_prefix = if let Some(pos) = answer.find("</think>") {
            let think = answer[..pos + "</think>".len()].to_string();
            answer = answer[pos + "</think>".len()..].to_string();
            think
        } else {
            String::new()
        };

        // 6. Citation formatting (citation_plus + repair)
        let cited: HashSet<usize> = if cfg.citation_plus {
            answer = self.citation_plus_pass(&answer, &knowledge).await?;
            let (repaired, idx) = repair_bad_citation_formats(&answer, num_chunks.max(1));
            answer = repaired;
            idx
        } else {
            extract_cited_indexes(&answer)
        };

        // 7. Reflection (optional second generation)
        let mut reflection: Option<String> = None;
        if cfg.reflect {
            let tool_calls = vec![("retrieval".to_string(), knowledge.clone())];
            let reflection_text = self
                .reflect_pass(question, &tool_calls, &final_question)
                .await?;
            reflection = Some(reflection_text.clone());
            if cfg.reflect_regenerate {
                let mut system = msgs[0].content.clone();
                system.push_str("\n\n**Reflection**\n");
                system.push_str(&reflection_text);
                let mut msgs2 = vec![ChatMessage::new("system", system)];
                msgs2.extend(history.iter().filter(|m| m.role != "system").cloned());
                msgs2.push(ChatMessage::new("user", &final_question));
                answer = self.llm.chat(&msgs2).await?;
            }
        }

        // References: cited chunks only when citation formatting is on,
        // otherwise the full hit list (RAGFlow falls back to all docs when
        // no chunk was cited).
        let references: Vec<serde_json::Value> = if cfg.citation_plus && !cited.is_empty() {
            hits.iter()
                .enumerate()
                .filter(|(i, _)| cited.contains(i))
                .map(|(_, h)| chunk_reference(h))
                .collect()
        } else {
            hits.iter().map(chunk_reference).collect()
        };

        Ok(ChatOutcome {
            answer: format!("{think_prefix}{answer}"),
            question: final_question,
            cited_indexes: cited,
            references,
            prompt,
            reflection,
            multi_queries: generated_queries,
        })
    }

    fn retrieve(&self, query: &str, top_k: usize, kb_ids: &[String]) -> Vec<HybridSearchResult> {
        self.engine.hybrid_search_kbs(HybridSearchQuery {
            query,
            query_embedding: None,
            top_k,
            kb_ids,
            vector_weight: self.config.vector_weight,
            doc_ids: None,
            rank_feature: None,
        })
    }

    /// `full_question` rewrite — mirrors `generator.py::full_question`.
    /// Returns `None` when the model output is unusable (falls back to the
    /// original question).
    async fn rewrite_full_question(
        &self,
        question: &str,
        history: &[ChatMessage],
    ) -> crate::Result<Option<String>> {
        let conversation = form_conversation(history);
        let language = self
            .config
            .language
            .clone()
            .unwrap_or_else(|| detect_language(question));
        let prompt = build_full_question_prompt(&conversation, &language);
        let msgs = vec![
            ChatMessage::new("system", prompt),
            ChatMessage::new("user", "Output: "),
        ];
        let answer = strip_think(&self.llm.chat(&msgs).await?);
        if answer.contains("**ERROR**") || answer.trim().is_empty() {
            return Ok(None);
        }
        Ok(Some(answer))
    }

    /// `multi_queries_gen` — mirrors `generator.py::multi_queries_gen`.
    async fn generate_multi_queries(
        &self,
        question: &str,
        query: &str,
        retrieved_docs: &str,
    ) -> crate::Result<Option<Vec<MultiQuery>>> {
        let prompt = build_multi_queries_prompt(query, question, retrieved_docs, "");
        let msgs = vec![
            ChatMessage::new("system", prompt),
            ChatMessage::new("user", "Output:\n"),
        ];
        let answer = strip_think(&self.llm.chat(&msgs).await?);
        let queries = parse_multi_queries(&answer);
        if queries.is_empty() {
            return Ok(None);
        }
        Ok(Some(queries))
    }

    /// `citation_plus` second pass — mirrors `agent_with_tools.py`:
    /// `[{"role": "system", "content": citation_plus(sources)},
    ///   {"role": "user", "content": text}]`.
    async fn citation_plus_pass(&self, answer: &str, sources: &str) -> crate::Result<String> {
        let system = build_citation_plus_prompt(sources);
        let msgs = vec![
            ChatMessage::new("system", system),
            ChatMessage::new("user", answer),
        ];
        Ok(strip_think(&self.llm.chat(&msgs).await?))
    }

    /// `reflect` pass — mirrors `generator.py::reflect_async`.
    async fn reflect_pass(
        &self,
        question: &str,
        tool_calls: &[(String, String)],
        _final_question: &str,
    ) -> crate::Result<String> {
        let prompt = build_reflect_prompt(question, tool_calls);
        let msgs = vec![
            ChatMessage::new("system", DEFAULT_CHAT_SYSTEM_PROMPT),
            ChatMessage::new("user", prompt),
        ];
        Ok(strip_think(&self.llm.chat(&msgs).await?))
    }
}

// ── Prompt assembly (pure, unit-testable) ─────────────────────────

/// `form_conversation` — mirror of `generator.py::full_question`:
/// `USER: ...\nASSISTANT: ...` lines from user/assistant messages.
pub fn form_conversation(messages: &[ChatMessage]) -> String {
    let mut lines = Vec::new();
    for m in messages {
        if m.role != "user" && m.role != "assistant" {
            continue;
        }
        lines.push(format!("{}: {}", m.role.to_uppercase(), m.content));
    }
    lines.join("\n")
}

/// Lightweight language detection used when `config.language` is unset:
/// CJK characters → `Chinese`, otherwise `English`.
pub fn detect_language(text: &str) -> String {
    if text.chars().any(|c| {
        matches!(c,
            '\u{4E00}'..='\u{9FFF}' | '\u{3400}'..='\u{4DBF}'
        )
    }) {
        "Chinese".into()
    } else {
        "English".into()
    }
}

/// Render `RAGFLOW_FULL_QUESTION_PROMPT` with today/yesterday/tomorrow as
/// absolute ISO dates plus the conversation and language hint.
pub fn build_full_question_prompt(conversation: &str, language: &str) -> String {
    let today = iso_date_shift(0);
    let yesterday = iso_date_shift(-1);
    let tomorrow = iso_date_shift(1);
    let mut vars = HashMap::new();
    vars.insert("today", today.as_str());
    vars.insert("yesterday", yesterday.as_str());
    vars.insert("tomorrow", tomorrow.as_str());
    vars.insert("conversation", conversation);
    vars.insert("language", language);
    PromptLibrary::full_question().render(&vars)
}

/// Render `RAGFLOW_MULTI_QUERIES_GEN_PROMPT`.
pub fn build_multi_queries_prompt(
    original_query: &str,
    original_question: &str,
    retrieved_docs: &str,
    missing_info: &str,
) -> String {
    let mut vars = HashMap::new();
    vars.insert("original_query", original_query);
    vars.insert("original_question", original_question);
    vars.insert("retrieved_docs", retrieved_docs);
    vars.insert("missing_info", missing_info);
    PromptLibrary::multi_queries_gen().render(&vars)
}

/// Render `RAGFLOW_CITATION_PLUS_PROMPT` with the citation guidelines as the
/// `{example}` block and the knowledge tree as `{sources}`.
pub fn build_citation_plus_prompt(sources: &str) -> String {
    let example = PromptLibrary::citation_prompt().render(&HashMap::new());
    let mut vars = HashMap::new();
    vars.insert("example", example.as_str());
    vars.insert("sources", sources);
    PromptLibrary::citation_plus().render(&vars)
}

/// Render `RAGFLOW_REFLECT_PROMPT` — `{goal}` plus one block per tool call.
pub fn build_reflect_prompt(goal: &str, tool_calls: &[(String, String)]) -> String {
    let calls = tool_calls
        .iter()
        .map(|(name, result)| format!("Tool call: `{name}`\nResults: {result}"))
        .collect::<Vec<_>>()
        .join("\n\n");
    let mut vars = HashMap::new();
    vars.insert("goal", goal);
    vars.insert("tool_calls", calls.as_str());
    PromptLibrary::reflect().render(&vars)
}

/// `kb_prompt` layout — mirror of `generator.py::kb_prompt` + the
/// `"\n------\n" + "\n\n------\n\n".join(...)` knowledge assembly from
/// `dialog_service.async_chat`. Each chunk renders as:
/// ```text
/// ID: 0
/// ├── Title: ...
/// └── Content:
/// <content>
/// ```
pub fn format_knowledge(hits: &[HybridSearchResult]) -> String {
    let knowledges: Vec<String> = hits
        .iter()
        .enumerate()
        .map(|(i, hit)| {
            let mut block = format!("\nID: {i}");
            if !hit.chunk.doc_name.is_empty() {
                block.push_str(&format!("\n├── Title: {}", hit.chunk.doc_name));
            }
            block.push_str("\n└── Content:\n");
            block.push_str(&hit.chunk.content);
            block
        })
        .collect();
    if knowledges.is_empty() {
        return String::new();
    }
    format!("\n------\n{}", knowledges.join("\n\n------\n\n"))
}

/// Assemble the generation messages: system prompt + knowledge tree +
/// (optional citation guidelines) + non-system history + user question.
pub fn build_answer_messages(
    config: &ChatPipelineConfig,
    question: &str,
    history: &[ChatMessage],
    knowledge: &str,
) -> Vec<ChatMessage> {
    let mut system = config
        .system_prompt
        .clone()
        .unwrap_or_else(|| DEFAULT_CHAT_SYSTEM_PROMPT.to_string());
    if !knowledge.trim().is_empty() {
        system.push_str("\n\nRelevant document context:\n");
        system.push_str(knowledge);
    }
    if config.citation_plus {
        system.push_str("\n\n");
        system.push_str(&PromptLibrary::citation_prompt().render(&HashMap::new()));
    }
    let mut msgs = vec![ChatMessage::new("system", system)];
    msgs.extend(history.iter().filter(|m| m.role != "system").cloned());
    msgs.push(ChatMessage::new("user", question));
    msgs
}

/// Parse the `multi_queries_gen` JSON output. Accepts the documented shape
/// `{"reasoning": ..., "questions": [{"question", "query"}, ...]}` and, as a
/// fallback, any embedded JSON array of `{question, query}` objects.
/// Returns an empty vector for malformed output.
pub fn parse_multi_queries(json: &str) -> Vec<MultiQuery> {
    let mut out = Vec::new();
    if let Ok(value) = serde_json::from_str::<serde_json::Value>(json)
        && let Some(questions) = value.get("questions").and_then(|q| q.as_array()) {
            collect_queries(questions, &mut out);
            return out;
        }
    // Fallback: extract the first bracketed JSON array.
    if let Some(start) = json.find('[')
        && let Some(end) = json.rfind(']')
            && end > start
                && let Ok(value) = serde_json::from_str::<serde_json::Value>(&json[start..=end])
                    && let Some(questions) = value.as_array() {
                        collect_queries(questions, &mut out);
                    }
    out
}

fn collect_queries(items: &[serde_json::Value], out: &mut Vec<MultiQuery>) {
    for item in items {
        let question = item.get("question").and_then(|v| v.as_str()).unwrap_or("");
        let query = item.get("query").and_then(|v| v.as_str()).unwrap_or("");
        if !question.is_empty() && !query.is_empty() {
            out.push(MultiQuery {
                question: question.to_string(),
                query: query.to_string(),
            });
        }
    }
}

/// Strip everything up to and including the last `</think>` marker —
/// mirror of RAGFlow `re.sub(r"^.*</think>", "", ans, flags=re.DOTALL)`.
pub fn strip_think(text: &str) -> String {
    match text.rfind("</think>") {
        Some(pos) => text[pos + "</think>".len()..].trim_start().to_string(),
        None => text.to_string(),
    }
}

fn chunk_reference(hit: &HybridSearchResult) -> serde_json::Value {
    serde_json::json!({
        "chunk_id": hit.chunk.id,
        "doc_name": hit.chunk.doc_name,
        "score": hit.score,
    })
}

/// ISO date `YYYY-MM-DD` shifted by `days` from today (UTC).
fn iso_date_shift(days: i64) -> String {
    let now = time::OffsetDateTime::now_utc() + time::Duration::days(days);
    format!(
        "{:04}-{:02}-{:02}",
        now.year(),
        now.month() as u8,
        now.day()
    )
}

fn env_flag(name: &str) -> bool {
    std::env::var(name)
        .map(|v| matches!(v.to_ascii_lowercase().as_str(), "1" | "true" | "on" | "yes"))
        .unwrap_or(false)
}

fn env_usize(name: &str) -> Option<usize> {
    std::env::var(name).ok().and_then(|v| v.trim().parse().ok())
}

fn env_f32(name: &str) -> Option<f32> {
    std::env::var(name).ok().and_then(|v| v.trim().parse().ok())
}

fn kb_flag(flags: &HashMap<String, String>, key: &str) -> bool {
    flags
        .get(key)
        .map(|v| matches!(v.to_ascii_lowercase().as_str(), "1" | "true" | "on" | "yes"))
        .unwrap_or(false)
}

fn kb_usize(flags: &HashMap<String, String>, key: &str) -> Option<usize> {
    flags.get(key).and_then(|v| v.trim().parse().ok())
}

fn kb_f32(flags: &HashMap<String, String>, key: &str) -> Option<f32> {
    flags.get(key).and_then(|v| v.trim().parse().ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hits(n: usize) -> Vec<HybridSearchResult> {
        (0..n)
            .map(|i| HybridSearchResult {
                chunk: crate::search::IndexedChunk {
                    id: format!("chunk-{i}"),
                    doc_name: format!("doc-{i}"),
                    content: format!("content number {i}"),
                    embedding: Vec::new(),
                    token_count: 3,
                    position: i,
                    metadata: HashMap::new(),
                },
                score: 1.0 - i as f32 * 0.1,
                vector_score: 0.0,
                term_score: 0.0,
                model_term_score: 0.0,
                rank_feature_score: 0.0,
                rank: i,
            })
            .collect()
    }

    fn config_with_flags() -> ChatPipelineConfig {
        ChatPipelineConfig {
            full_question: true,
            multi_queries: true,
            multi_queries_top_k: 3,
            citation_plus: true,
            reflect: true,
            ..ChatPipelineConfig::default()
        }
    }

    #[test]
    fn defaults_keep_every_feature_off() {
        let cfg = ChatPipelineConfig::default();
        assert!(!cfg.full_question);
        assert!(!cfg.multi_queries);
        assert!(!cfg.citation_plus);
        assert!(!cfg.reflect);
        assert!(!cfg.reflect_regenerate);
        assert_eq!(cfg.top_k, 4);
        assert_eq!(cfg.multi_queries_top_k, 0);
    }

    #[test]
    fn kb_flags_turn_features_on_and_parse_numbers() {
        let mut cfg = ChatPipelineConfig::default();
        let flags = HashMap::from([
            ("chat_full_question".to_string(), "true".to_string()),
            ("chat_multi_queries".to_string(), "1".to_string()),
            ("chat_citation_plus".to_string(), "yes".to_string()),
            ("chat_multi_queries_top_k".to_string(), "5".to_string()),
            ("chat_top_k".to_string(), "8".to_string()),
        ]);
        cfg.apply_kb_flags(&flags);
        assert!(cfg.full_question);
        assert!(cfg.multi_queries);
        assert!(cfg.citation_plus);
        assert!(!cfg.reflect);
        assert_eq!(cfg.multi_queries_top_k, 5);
        assert_eq!(cfg.top_k, 8);
    }

    #[test]
    fn full_question_prompt_embeds_conversation_dates_and_language() {
        let msgs = vec![
            ChatMessage::new("user", "What is the name of Donald Trump's father?"),
            ChatMessage::new("assistant", "Fred Trump."),
            ChatMessage::new("user", "And his mother?"),
        ];
        let conversation = form_conversation(&msgs);
        assert_eq!(
            conversation,
            "USER: What is the name of Donald Trump's father?\n\
             ASSISTANT: Fred Trump.\n\
             USER: And his mother?"
        );

        let rendered = build_full_question_prompt(&conversation, "English");
        assert!(rendered.contains("USER: What is the name of Donald Trump's father?"));
        assert!(rendered.contains("ASSISTANT: Fred Trump."));
        assert!(rendered.contains(&iso_date_shift(0)));
        assert!(rendered.contains(&iso_date_shift(-1)));
        assert!(rendered.contains(&iso_date_shift(1)));
        // All Jinja placeholders must be substituted away.
        assert!(!rendered.contains("{today}"));
        assert!(!rendered.contains("{conversation}"));
        assert!(!rendered.contains("{language}"));
    }

    #[test]
    fn multi_queries_prompt_renders_and_parses_branch() {
        let rendered = build_multi_queries_prompt(
            "RAGFlow deployment",
            "How do I deploy RAGFlow?",
            "ID: 0\n└── Content: nothing useful",
            "memory requirements",
        );
        assert!(rendered.contains("Original query:\nRAGFlow deployment"));
        assert!(rendered.contains("How do I deploy RAGFlow?"));
        assert!(rendered.contains("memory requirements"));
        assert!(rendered.contains("\"questions\""));

        // Documented JSON shape parses into 2-3 queries.
        let queries = parse_multi_queries(
            r#"{"reasoning": "split", "questions": [
                {"question": "Q1", "query": "query one"},
                {"question": "Q2", "query": "query two"}
            ]}"#,
        );
        assert_eq!(queries.len(), 2);
        assert_eq!(queries[0].query, "query one");
        assert_eq!(queries[1].question, "Q2");

        // Embedded-array fallback works when the model adds prose.
        let queries = parse_multi_queries(
            "Here are the queries:\n[{\"question\": \"A\", \"query\": \"a\"}, {\"question\": \"B\", \"query\": \"b\"}]",
        );
        assert_eq!(queries.len(), 2);

        // Garbage yields an empty branch.
        assert!(parse_multi_queries("**ERROR**").is_empty());
        assert!(parse_multi_queries("").is_empty());
    }

    #[test]
    fn citation_plus_prompt_contains_guidelines_and_sources() {
        let sources = format_knowledge(&hits(2));
        assert!(sources.contains("ID: 0"));
        assert!(sources.contains("├── Title: doc-0"));
        assert!(sources.contains("└── Content:\ncontent number 0"));

        let rendered = build_citation_plus_prompt(&sources);
        assert!(rendered.contains("adding correct citations"));
        assert!(rendered.contains("content number 1"));
        assert!(!rendered.contains("{sources}"));
        assert!(!rendered.contains("{example}"));

        // Answer messages carry the citation guidelines when enabled.
        let cfg = config_with_flags();
        let msgs = build_answer_messages(&cfg, "question?", &[], &sources);
        assert_eq!(msgs[0].role, "system");
        assert!(msgs[0].content.contains("Relevant document context:"));
        assert!(msgs[0].content.contains("add citations to the input text"));
        assert_eq!(msgs[1].role, "user");
        assert_eq!(msgs[1].content, "question?");

        // With citation formatting off, the guidelines are NOT appended.
        let msgs =
            build_answer_messages(&ChatPipelineConfig::default(), "question?", &[], &sources);
        assert!(!msgs[0].content.contains("add citations to the input text"));
    }

    #[test]
    fn answer_post_processing_canonicalizes_citations() {
        // repair_bad_citation_formats integration (dialog.rs): mixed bad
        // formats become canonical [ID:n] markers; out-of-range stay verbatim.
        let (repaired, idx) = repair_bad_citation_formats(
            "答案见 (ID: 12)、[ID: 3] 与 ref9，但 (ID: 99) 超范围。",
            20,
        );
        assert_eq!(
            repaired,
            "答案见 [ID:12]、[ID:3] 与 [ID:9]，但 (ID: 99) 超范围。"
        );
        assert_eq!(idx, HashSet::from([12, 3, 9]));

        // extract_cited_indexes picks up canonical markers from raw output;
        // bad formats must pass through repair first (as in the pipeline).
        let cited = extract_cited_indexes("参考 [ID:1] 与 [ID:2] 以及 (ID: 7)");
        assert_eq!(cited, HashSet::from([1, 2]));
        let (repaired, idx) = repair_bad_citation_formats("参考 (ID: 7)", 20);
        assert_eq!(repaired, "参考 [ID:7]");
        assert_eq!(idx, HashSet::from([7]));
        assert_eq!(extract_cited_indexes(&repaired), HashSet::from([7]));
    }

    #[test]
    fn reflect_prompt_renders_goal_and_tool_calls() {
        let rendered = build_reflect_prompt(
            "Answer the user question",
            &[(
                "retrieval".to_string(),
                "ID: 0\n└── Content: found it".to_string(),
            )],
        );
        assert!(rendered.contains("To achieve the goal: Answer the user question"));
        assert!(rendered.contains("Tool call: `retrieval`"));
        assert!(rendered.contains("found it"));
        assert!(!rendered.contains("{goal}"));
        assert!(!rendered.contains("{tool_calls}"));
    }

    #[test]
    fn strip_think_removes_leading_think_blocks() {
        assert_eq!(strip_think("思考中</think>答案"), "答案");
        assert_eq!(strip_think("no think block"), "no think block");
        assert_eq!(strip_think("a</think>b</think>c"), "c");
    }
}
