//! Pure-Rust document writers used by the Agent `DocGenerator` component.
//!
//! The fixed RAGFlow Python component shells out to Pandoc/XeLaTeX, while the
//! fixed Go port provides small in-process writers.  RayRAG follows the latter
//! shape so Canvas execution remains a single Rust process.  The writers are
//! deliberately bounded and keep the generated bytes in memory for the
//! attachment descriptor produced by `agent.rs`.

use anyhow::{Result, anyhow, bail};
use lopdf::content::{Content, Operation};
use lopdf::{Document, Object, Stream, StringFormat, dictionary};
use std::collections::{BTreeMap, BTreeSet};
use std::io::{Cursor, Write};

const PDF_PAGE_WIDTH: i64 = 595;
const PDF_PAGE_HEIGHT: i64 = 842;

#[derive(Debug, Clone)]
pub struct DocumentWriterOptions<'a> {
    pub header_text: &'a str,
    pub footer_text: &'a str,
    pub watermark_text: &'a str,
    pub add_page_numbers: bool,
    pub add_timestamp: bool,
    pub font_size: u16,
    pub font_family: &'a str,
    pub generated_at: &'a str,
}

impl<'a> DocumentWriterOptions<'a> {
    #[cfg(test)]
    fn minimal(generated_at: &'a str) -> Self {
        Self {
            header_text: "",
            footer_text: "",
            watermark_text: "",
            add_page_numbers: false,
            add_timestamp: false,
            font_size: 0,
            font_family: "",
            generated_at,
        }
    }
}

/// Match the fixed Go TXT writer: metadata lines, one blank separator, body,
/// and an optional footer. UTF-8 is the only output encoding.
pub fn write_txt(content: &str, options: &DocumentWriterOptions<'_>) -> Vec<u8> {
    let mut output = String::new();
    if !options.header_text.is_empty() {
        output.push_str(options.header_text);
        output.push('\n');
    }
    if options.add_timestamp {
        output.push_str("Generated: ");
        output.push_str(options.generated_at);
        output.push('\n');
    }
    output.push('\n');
    output.push_str(content);
    if !options.footer_text.is_empty() {
        output.push('\n');
        output.push_str(options.footer_text);
    }
    output.into_bytes()
}

/// Preserve Markdown verbatim and represent non-rendering metadata as HTML
/// comments, following the fixed Go writer contract.
pub fn write_markdown(content: &str, options: &DocumentWriterOptions<'_>) -> Vec<u8> {
    let mut output = String::new();
    if options.add_timestamp {
        output.push_str("<!-- generated: ");
        output.push_str(options.generated_at);
        output.push_str(" -->\n\n");
    }
    if !options.header_text.is_empty() {
        output.push_str("<!-- header: ");
        output.push_str(options.header_text);
        output.push_str(" -->\n\n");
    }
    output.push_str(content);
    if !options.footer_text.is_empty() {
        output.push_str("\n\n<!-- footer: ");
        output.push_str(options.footer_text);
        output.push_str(" -->\n");
    }
    output.into_bytes()
}

/// Wrap the supplied body in the fixed self-contained HTML5 structure.
/// Content and decorations intentionally pass through without escaping,
/// matching the upstream Go writer's caller-owned sanitization contract.
pub fn write_html(content: &str, options: &DocumentWriterOptions<'_>) -> Vec<u8> {
    let title = if options.header_text.is_empty() {
        "Document"
    } else {
        options.header_text
    };
    let font_size = if options.font_size == 0 {
        11
    } else {
        options.font_size
    };
    let font_family = if options.font_family.is_empty() {
        "sans-serif"
    } else {
        options.font_family
    };
    let mut output = format!(
        concat!(
            "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n",
            "<meta charset=\"utf-8\">\n<title>{title}</title>\n<style>\n",
            "body {{ font-family: \"{font_family}\"; font-size: {font_size}pt; line-height: 1.5; }}\n"
        ),
        title = title,
        font_size = font_size,
        font_family = font_family
    );
    if !options.watermark_text.is_empty() {
        output.push_str(".watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-30deg); font-size: 96pt; color: rgba(0,0,0,0.06); pointer-events: none; z-index: -1; }\n");
    }
    output.push_str("</style>\n</head>\n<body>\n");
    if !options.header_text.is_empty() {
        output.push_str("<header>");
        output.push_str(options.header_text);
        output.push_str("</header>\n");
    }
    if !options.watermark_text.is_empty() {
        output.push_str("<div class=\"watermark\">");
        output.push_str(options.watermark_text);
        output.push_str("</div>\n");
    }
    output.push_str("<main>\n");
    output.push_str(content);
    output.push_str("\n</main>\n");
    if !options.footer_text.is_empty() {
        output.push_str("<footer>");
        output.push_str(options.footer_text);
        output.push_str("</footer>\n");
    }
    if options.add_timestamp {
        output.push_str("<p><small>Generated: ");
        output.push_str(options.generated_at);
        output.push_str("</small></p>\n");
    }
    output.push_str("</body>\n</html>\n");
    output.into_bytes()
}

/// Build a minimal Word-compatible OOXML package without invoking Pandoc.
pub fn write_docx(content: &str, options: &DocumentWriterOptions<'_>) -> Result<Vec<u8>> {
    let has_header = !options.header_text.is_empty() || !options.watermark_text.is_empty();
    let has_footer =
        !options.footer_text.is_empty() || options.add_page_numbers || options.add_timestamp;
    let font_size = if options.font_size == 0 {
        12
    } else {
        options.font_size
    };
    let font = xml_escape(if options.font_family.is_empty() {
        "Noto Sans CJK SC"
    } else {
        options.font_family
    });
    let half_points = u32::from(font_size) * 2;

    let mut document_body = String::new();
    let lines = content.split('\n').map(|line| line.trim_end_matches('\r'));
    for line in lines {
        document_body.push_str(&format!(
            "<w:p><w:r><w:rPr><w:sz w:val=\"{half_points}\"/><w:szCs w:val=\"{half_points}\"/><w:rFonts w:ascii=\"{font}\" w:eastAsia=\"{font}\" w:hAnsi=\"{font}\"/></w:rPr><w:t xml:space=\"preserve\">{}</w:t></w:r></w:p>\n",
            xml_escape(line)
        ));
    }
    let header_reference = if has_header {
        "<w:headerReference w:type=\"default\" r:id=\"rIdHeader1\"/>"
    } else {
        ""
    };
    let footer_reference = if has_footer {
        "<w:footerReference w:type=\"default\" r:id=\"rIdFooter1\"/>"
    } else {
        ""
    };
    let document_xml = format!(
        concat!(
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n",
            "<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">\n",
            "<w:body>\n{document_body}<w:sectPr>{header_reference}{footer_reference}",
            "<w:pgSz w:w=\"12240\" w:h=\"15840\"/>",
            "<w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\" w:header=\"720\" w:footer=\"720\" w:gutter=\"0\"/>",
            "<w:cols w:space=\"720\"/><w:docGrid w:linePitch=\"360\"/>",
            "</w:sectPr>\n</w:body>\n</w:document>"
        ),
        document_body = document_body,
        header_reference = header_reference,
        footer_reference = footer_reference
    );

    let styles_xml = format!(
        concat!(
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>",
            "<w:styles xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\">",
            "<w:docDefaults><w:rPrDefault><w:rPr>",
            "<w:rFonts w:ascii=\"{font}\" w:eastAsia=\"{font}\" w:hAnsi=\"{font}\" w:cs=\"Times New Roman\"/>",
            "<w:sz w:val=\"{half_points}\"/><w:szCs w:val=\"{half_points}\"/><w:lang w:val=\"en-US\" w:eastAsia=\"zh-CN\"/>",
            "</w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after=\"160\" w:line=\"259\" w:lineRule=\"auto\"/></w:pPr></w:pPrDefault></w:docDefaults>",
            "<w:style w:type=\"paragraph\" w:default=\"1\" w:styleId=\"Normal\"><w:name w:val=\"Normal\"/><w:qFormat/></w:style>",
            "<w:style w:type=\"paragraph\" w:styleId=\"Header\"><w:name w:val=\"header\"/><w:basedOn w:val=\"Normal\"/><w:pPr><w:jc w:val=\"center\"/></w:pPr></w:style>",
            "<w:style w:type=\"paragraph\" w:styleId=\"Footer\"><w:name w:val=\"footer\"/><w:basedOn w:val=\"Normal\"/><w:pPr><w:jc w:val=\"center\"/></w:pPr></w:style>",
            "</w:styles>"
        ),
        font = font,
        half_points = half_points
    );

    let mut relationships = String::from(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rIdStyles\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/>",
    );
    if has_header {
        relationships.push_str("<Relationship Id=\"rIdHeader1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/header\" Target=\"header1.xml\"/>");
    }
    if has_footer {
        relationships.push_str("<Relationship Id=\"rIdFooter1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer\" Target=\"footer1.xml\"/>");
    }
    relationships.push_str("</Relationships>");

    let header_xml = build_docx_header(options, half_points, &font);
    let footer_xml = build_docx_footer(options, half_points, &font);

    let cursor = Cursor::new(Vec::new());
    let mut archive = zip::ZipWriter::new(cursor);
    let zip_options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);
    write_zip_entry(
        &mut archive,
        "[Content_Types].xml",
        DOCX_CONTENT_TYPES,
        zip_options,
    )?;
    write_zip_entry(&mut archive, "_rels/.rels", DOCX_PACKAGE_RELS, zip_options)?;
    write_zip_entry(
        &mut archive,
        "word/_rels/document.xml.rels",
        relationships.as_bytes(),
        zip_options,
    )?;
    write_zip_entry(
        &mut archive,
        "word/styles.xml",
        styles_xml.as_bytes(),
        zip_options,
    )?;
    write_zip_entry(
        &mut archive,
        "word/document.xml",
        document_xml.as_bytes(),
        zip_options,
    )?;
    if has_header {
        write_zip_entry(
            &mut archive,
            "word/header1.xml",
            header_xml.as_bytes(),
            zip_options,
        )?;
    }
    if has_footer {
        write_zip_entry(
            &mut archive,
            "word/footer1.xml",
            footer_xml.as_bytes(),
            zip_options,
        )?;
    }
    Ok(archive.finish()?.into_inner())
}

fn build_docx_header(options: &DocumentWriterOptions<'_>, half_points: u32, font: &str) -> String {
    let mut header = String::from(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><w:hdr xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">",
    );
    if !options.watermark_text.is_empty() {
        header.push_str(&format!(
            concat!(
                "<w:p><w:r><w:pict><v:shapetype id=\"_x0000_t136\" coordsize=\"21600,21600\" o:spt=\"136\" path=\"m@7,l@8,m@5,21600l@6,21600e\">",
                "<v:textpath on=\"t\" fitshape=\"t\"/><o:lock v:ext=\"edit\" text=\"t\" shapetype=\"t\"/></v:shapetype>",
                "<v:shape id=\"watermark\" o:spid=\"_x0000_s1026\" type=\"#_x0000_t136\" style=\"position:absolute;width:500pt;height:90pt;rotation:315;z-index:-251658240;mso-position-horizontal:center;mso-position-horizontal-relative:margin;mso-position-vertical:center;mso-position-vertical-relative:margin\" fillcolor=\"#d9d9d9\" stroked=\"f\">",
                "<v:fill opacity=\".5\"/><v:textpath style=\"font-family:&quot;Calibri&quot;;font-size:1pt\" string=\"{}\"/>",
                "</v:shape></w:pict></w:r></w:p>"
            ),
            xml_escape(options.watermark_text)
        ));
    }
    if !options.header_text.is_empty() {
        header.push_str(&format!(
            "<w:p><w:pPr><w:pStyle w:val=\"Header\"/><w:jc w:val=\"center\"/></w:pPr><w:r><w:rPr><w:sz w:val=\"{half_points}\"/><w:rFonts w:ascii=\"{font}\" w:eastAsia=\"{font}\" w:hAnsi=\"{font}\"/></w:rPr><w:t xml:space=\"preserve\">{}</w:t></w:r></w:p>",
            xml_escape(options.header_text)
        ));
    }
    header.push_str("</w:hdr>");
    header
}

fn build_docx_footer(options: &DocumentWriterOptions<'_>, half_points: u32, font: &str) -> String {
    let run_properties = format!(
        "<w:rPr><w:sz w:val=\"{half_points}\"/><w:rFonts w:ascii=\"{font}\" w:eastAsia=\"{font}\" w:hAnsi=\"{font}\"/></w:rPr>"
    );
    let mut footer = String::from(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><w:ftr xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><w:p><w:pPr><w:pStyle w:val=\"Footer\"/><w:jc w:val=\"center\"/></w:pPr>",
    );
    if !options.footer_text.is_empty() {
        footer.push_str(&format!(
            "<w:r>{run_properties}<w:t xml:space=\"preserve\">{}</w:t></w:r>",
            xml_escape(options.footer_text)
        ));
        if options.add_page_numbers || options.add_timestamp {
            footer.push_str("<w:r><w:t xml:space=\"preserve\"> | </w:t></w:r>");
        }
    }
    if options.add_page_numbers {
        footer.push_str(&format!(concat!(
            "<w:r>{run_properties}<w:t xml:space=\"preserve\">Page </w:t></w:r>",
            "<w:r><w:fldChar w:fldCharType=\"begin\"/></w:r>",
            "<w:r>{run_properties}<w:instrText xml:space=\"preserve\"> PAGE </w:instrText></w:r>",
            "<w:r><w:fldChar w:fldCharType=\"separate\"/></w:r>",
            "<w:r>{run_properties}<w:t>1</w:t></w:r>",
            "<w:r><w:fldChar w:fldCharType=\"end\"/></w:r>"
        ), run_properties = run_properties));
        if options.add_timestamp {
            footer.push_str("<w:r><w:t xml:space=\"preserve\"> | </w:t></w:r>");
        }
    }
    if options.add_timestamp {
        footer.push_str(&format!(
            "<w:r>{run_properties}<w:t xml:space=\"preserve\">{}</w:t></w:r>",
            xml_escape(options.generated_at)
        ));
    }
    footer.push_str("</w:p></w:ftr>");
    footer
}

/// Create an in-memory A4 PDF with a Unicode extraction map. This removes the
/// fixed Python implementation's XeLaTeX runtime requirement while retaining
/// its body/decorations/page-number output surface.
pub fn write_pdf(content: &str, options: &DocumentWriterOptions<'_>) -> Result<Vec<u8>> {
    let font_size = i64::from(if options.font_size == 0 {
        12
    } else {
        options.font_size
    });
    let line_height = (font_size * 3 / 2).max(1);
    let max_lines = ((770 - 70) / line_height).max(1) as usize;
    let mut lines = content
        .split('\n')
        .map(|line| line.trim_end_matches('\r').to_owned())
        .collect::<Vec<_>>();
    if lines.is_empty() {
        lines.push(String::new());
    }
    let pages = lines
        .chunks(max_lines)
        .map(<[_]>::to_vec)
        .collect::<Vec<_>>();

    let mut all_text = BTreeSet::new();
    for text in std::iter::once(content).chain([
        options.header_text,
        options.footer_text,
        options.watermark_text,
    ]) {
        all_text.extend(text.chars());
    }
    all_text.extend(options.generated_at.chars());
    all_text.extend("Generated: |Page 0123456789".chars());
    if all_text.len() > usize::from(u16::MAX - 1) {
        bail!("PDF contains too many distinct Unicode scalar values");
    }
    let codes = all_text
        .into_iter()
        .enumerate()
        .map(|(index, character)| (character, (index + 1) as u16))
        .collect::<BTreeMap<_, _>>();

    let mut document = Document::with_version("1.5");
    let pages_id = document.new_object_id();
    let cmap = unicode_cmap(&codes);
    let cmap_id = document.add_object(Stream::new(dictionary! {}, cmap.into_bytes()));
    let descendant_id = document.add_object(dictionary! {
        "Type" => "Font",
        "Subtype" => "CIDFontType0",
        "BaseFont" => "STSong-Light",
        "CIDSystemInfo" => dictionary! {
            "Registry" => Object::string_literal("Adobe"),
            "Ordering" => Object::string_literal("Identity"),
            "Supplement" => 0,
        },
        "DW" => 1000,
    });
    let font_id = document.add_object(dictionary! {
        "Type" => "Font",
        "Subtype" => "Type0",
        "BaseFont" => "STSong-Light",
        "Encoding" => "Identity-H",
        "DescendantFonts" => vec![Object::Reference(descendant_id)],
        "ToUnicode" => Object::Reference(cmap_id),
    });
    let resources_id = document.add_object(dictionary! {
        "Font" => dictionary! { "F1" => font_id },
    });

    let mut page_ids = Vec::with_capacity(pages.len());
    for (page_index, page_lines) in pages.iter().enumerate() {
        let mut operations = Vec::new();
        if !options.watermark_text.is_empty() {
            push_pdf_text(
                &mut operations,
                options.watermark_text,
                &codes,
                120,
                410,
                42,
                true,
                true,
            )?;
        }
        if !options.header_text.is_empty() {
            push_pdf_text(
                &mut operations,
                options.header_text,
                &codes,
                36,
                810,
                (font_size - 2).max(8),
                false,
                false,
            )?;
        }
        let mut y = 770;
        for line in page_lines {
            if !line.is_empty() {
                push_pdf_text(
                    &mut operations,
                    line,
                    &codes,
                    36,
                    y,
                    font_size,
                    false,
                    false,
                )?;
            }
            y -= line_height;
        }
        let mut footer_parts = Vec::new();
        if !options.footer_text.is_empty() {
            footer_parts.push(options.footer_text.to_owned());
        }
        if options.add_timestamp {
            footer_parts.push(options.generated_at.to_owned());
        }
        if options.add_page_numbers {
            footer_parts.push(format!("Page {}", page_index + 1));
        }
        if !footer_parts.is_empty() {
            push_pdf_text(
                &mut operations,
                &footer_parts.join(" | "),
                &codes,
                36,
                25,
                (font_size - 2).max(8),
                false,
                false,
            )?;
        }
        let content_stream = Content { operations }.encode()?;
        let content_id = document.add_object(Stream::new(dictionary! {}, content_stream));
        page_ids.push(document.add_object(dictionary! {
            "Type" => "Page",
            "Parent" => pages_id,
            "Contents" => content_id,
        }));
    }
    document.objects.insert(
        pages_id,
        Object::Dictionary(dictionary! {
            "Type" => "Pages",
            "Kids" => page_ids.iter().copied().map(Object::Reference).collect::<Vec<_>>(),
            "Count" => page_ids.len() as i64,
            "Resources" => resources_id,
            "MediaBox" => vec![0.into(), 0.into(), PDF_PAGE_WIDTH.into(), PDF_PAGE_HEIGHT.into()],
        }),
    );
    let catalog_id = document.add_object(dictionary! {
        "Type" => "Catalog",
        "Pages" => pages_id,
    });
    let info_id = document.add_object(dictionary! {
        "Creator" => Object::string_literal("RayRAG DocGenerator"),
    });
    document.trailer.set("Root", catalog_id);
    document.trailer.set("Info", info_id);
    document.compress();
    let mut bytes = Vec::new();
    document.save_to(&mut bytes)?;
    Ok(bytes)
}

#[allow(clippy::too_many_arguments)]
fn push_pdf_text(
    operations: &mut Vec<Operation>,
    text: &str,
    codes: &BTreeMap<char, u16>,
    x: i64,
    y: i64,
    font_size: i64,
    grey: bool,
    rotated: bool,
) -> Result<()> {
    let encoded = encode_pdf_text(text, codes)?;
    if grey {
        operations.push(Operation::new(
            "rg",
            vec![Object::Real(0.82), Object::Real(0.82), Object::Real(0.82)],
        ));
    } else {
        operations.push(Operation::new(
            "rg",
            vec![Object::Real(0.0), Object::Real(0.0), Object::Real(0.0)],
        ));
    }
    operations.push(Operation::new("BT", vec![]));
    operations.push(Operation::new("Tf", vec!["F1".into(), font_size.into()]));
    if rotated {
        operations.push(Operation::new(
            "Tm",
            vec![
                Object::Real(0.707),
                Object::Real(0.707),
                Object::Real(-0.707),
                Object::Real(0.707),
                x.into(),
                y.into(),
            ],
        ));
    } else {
        operations.push(Operation::new("Td", vec![x.into(), y.into()]));
    }
    operations.push(Operation::new(
        "Tj",
        vec![Object::String(encoded, StringFormat::Hexadecimal)],
    ));
    operations.push(Operation::new("ET", vec![]));
    Ok(())
}

fn encode_pdf_text(text: &str, codes: &BTreeMap<char, u16>) -> Result<Vec<u8>> {
    let mut encoded = Vec::with_capacity(text.len() * 2);
    for character in text.chars() {
        let code = codes
            .get(&character)
            .ok_or_else(|| anyhow!("missing PDF character map for U+{:04X}", character as u32))?;
        encoded.extend_from_slice(&code.to_be_bytes());
    }
    Ok(encoded)
}

fn unicode_cmap(codes: &BTreeMap<char, u16>) -> String {
    let mut cmap = String::from(concat!(
        "/CIDInit /ProcSet findresource begin\n12 dict begin\nbegincmap\n",
        "/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def\n",
        "/CMapName /RayRAG-Identity-UCS def\n/CMapType 2 def\n",
        "1 begincodespacerange\n<0000> <FFFF>\nendcodespacerange\n"
    ));
    let entries = codes.iter().collect::<Vec<_>>();
    for chunk in entries.chunks(100) {
        cmap.push_str(&format!("{} beginbfchar\n", chunk.len()));
        for (character, code) in chunk {
            let unicode = character
                .encode_utf16(&mut [0_u16; 2])
                .iter()
                .map(|unit| format!("{unit:04X}"))
                .collect::<String>();
            cmap.push_str(&format!("<{code:04X}> <{unicode}>\n"));
        }
        cmap.push_str("endbfchar\n");
    }
    cmap.push_str("endcmap\nCMapName currentdict /CMap defineresource pop\nend\nend\n");
    cmap
}

fn write_zip_entry<W: Write + std::io::Seek>(
    archive: &mut zip::ZipWriter<W>,
    name: &str,
    bytes: &[u8],
    options: zip::write::SimpleFileOptions,
) -> Result<()> {
    archive.start_file(name, options)?;
    archive.write_all(bytes)?;
    Ok(())
}

fn xml_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

const DOCX_CONTENT_TYPES: &[u8] = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml" ContentType="application/xml"/>
<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
<Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/>
<Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>
</Types>"#;

const DOCX_PACKAGE_RELS: &[u8] = br#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>"#;

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;

    const NOW: &str = "2026-06-15T12:00:00Z";

    #[test]
    fn text_writers_match_the_fixed_go_layouts() {
        let mut options = DocumentWriterOptions::minimal(NOW);
        assert_eq!(write_txt("hello", &options), b"\nhello");
        assert_eq!(write_markdown("# Hello", &options), b"# Hello");

        options.header_text = "H";
        options.footer_text = "F";
        options.add_timestamp = true;
        assert_eq!(
            String::from_utf8(write_txt("body", &options)).unwrap(),
            "H\nGenerated: 2026-06-15T12:00:00Z\n\nbody\nF"
        );
        assert_eq!(
            String::from_utf8(write_markdown("body", &options)).unwrap(),
            "<!-- generated: 2026-06-15T12:00:00Z -->\n\n<!-- header: H -->\n\nbody\n\n<!-- footer: F -->\n"
        );
    }

    #[test]
    fn html_writer_keeps_the_fixed_wrapper_and_raw_body_contract() {
        let default_output =
            String::from_utf8(write_html("body", &DocumentWriterOptions::minimal(NOW))).unwrap();
        assert!(default_output.contains("font-family: \"sans-serif\""));
        assert!(default_output.contains("font-size: 11pt"));

        let mut options = DocumentWriterOptions::minimal(NOW);
        options.header_text = "My Doc";
        options.watermark_text = "DRAFT";
        options.add_timestamp = true;
        options.font_size = 12;
        options.font_family = "Noto Sans CJK SC";
        let output = String::from_utf8(write_html("<b>bold</b>", &options)).unwrap();
        assert!(output.starts_with("<!DOCTYPE html>"));
        assert!(output.contains("<title>My Doc</title>"));
        assert!(output.contains("<main>\n<b>bold</b>\n</main>"));
        assert!(output.contains("<div class=\"watermark\">DRAFT</div>"));
        assert!(output.contains("Generated: 2026-06-15T12:00:00Z"));
    }

    #[test]
    fn docx_writer_emits_valid_zip_with_escaped_body_and_decorations() {
        let mut options = DocumentWriterOptions::minimal(NOW);
        options.header_text = "TOP";
        options.footer_text = "BOTTOM";
        options.watermark_text = "DRAFT";
        options.add_page_numbers = true;
        options.add_timestamp = true;
        let bytes = write_docx("A < B & 中文", &options).unwrap();
        assert!(bytes.starts_with(b"PK\x03\x04"));
        let mut archive = zip::ZipArchive::new(Cursor::new(bytes)).unwrap();
        let mut body = String::new();
        archive
            .by_name("word/document.xml")
            .unwrap()
            .read_to_string(&mut body)
            .unwrap();
        assert!(body.contains("A &lt; B &amp; 中文"));
        let mut header = String::new();
        archive
            .by_name("word/header1.xml")
            .unwrap()
            .read_to_string(&mut header)
            .unwrap();
        assert!(header.contains("TOP"));
        assert!(header.contains("DRAFT"));
        let mut footer = String::new();
        archive
            .by_name("word/footer1.xml")
            .unwrap()
            .read_to_string(&mut footer)
            .unwrap();
        assert!(footer.contains(" PAGE "));
        assert!(footer.contains(NOW));
        assert!(docx_rs::read_docx(archive.into_inner().get_ref()).is_ok());
    }

    #[test]
    fn pdf_writer_is_loadable_and_preserves_unicode_extraction() {
        let mut options = DocumentWriterOptions::minimal(NOW);
        options.header_text = "Header";
        options.add_page_numbers = true;
        let bytes = write_pdf("Hello 中文", &options).unwrap();
        assert!(bytes.starts_with(b"%PDF-"));
        let document = Document::load_mem(&bytes).unwrap();
        assert_eq!(document.get_pages().len(), 1);
        let text = document.extract_text(&[1]).unwrap();
        assert!(text.contains("Hello 中文"), "{text:?}");
        assert!(text.contains("Page 1"), "{text:?}");
    }
}
